# Generated by Django 5.0.3 on 2025-02-22 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custompage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custompage',
            options={'verbose_name_plural': 'Custom Pages'},
        ),
    ]
