services:
  web:
    build: .
    container_name: django_app
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8000"  # Change host port from 8000 to 8080
    volumes:
      - .:/app
    command: gunicorn --bind 0.0.0.0:8000 project_name.wsgi:application

  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
