# Generated by Django 5.0.3 on 2025-02-22 10:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0002_alter_policy_policy_texts_alter_terms_term_texts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_texts', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Refund Policy',
            },
        ),
        migrations.AlterModelOptions(
            name='policy',
            options={'verbose_name_plural': 'Privacy Policy'},
        ),
        migrations.AlterModelOptions(
            name='terms',
            options={'verbose_name_plural': 'Terms and Conditions'},
        ),
    ]
