# Generated by Django 5.0.3 on 2025-02-22 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0003_refund_alter_policy_options_alter_terms_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Refund',
        ),
        migrations.AlterModelOptions(
            name='policy',
            options={},
        ),
        migrations.AlterModelOptions(
            name='terms',
            options={},
        ),
    ]
