# Generated by Django 4.2.4 on 2023-10-18 05:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_pricingsection_button_text_pricingsection_button_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingsection',
            name='button_text',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='pricingsection',
            name='button_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='pricingsection',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricingsection',
            name='price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pricingsection',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pricingsection',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
