# Generated by Django 4.2.4 on 2023-09-20 19:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_subscriber_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
