# Generated by Django 4.2.4 on 2023-09-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expiration_time',
            field=models.DateTimeField(),
        ),
    ]
