# Generated by Django 4.2.4 on 2023-09-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='headerFooterSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_button_text', models.CharField(max_length=200)),
                ('header_button_url', models.CharField(max_length=1000)),
                ('footer_col1_description', models.TextField()),
                ('facebook', models.CharField(max_length=1000)),
                ('instagram', models.CharField(max_length=1000)),
                ('linkedin', models.CharField(max_length=1000)),
                ('twitter', models.CharField(max_length=1000)),
                ('quick_link_title', models.CharField(max_length=300)),
                ('quick_link_description', models.TextField()),
                ('footer_copyright', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SeoSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(max_length=500)),
                ('meta_description', models.TextField()),
                ('seo_keywords', models.TextField(default='software,application,marketer,developer')),
                ('meta_image', models.ImageField(upload_to='app_config/')),
                ('social_share_image', models.ImageField(upload_to='app_config/')),
            ],
        ),
        migrations.CreateModel(
            name='websiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Application Name', max_length=500)),
                ('logo', models.ImageField(upload_to='app_config/')),
                ('favicon', models.ImageField(upload_to='app_config/')),
                ('author', models.CharField(blank=True, default='Author Name', max_length=200, null=True)),
                ('email_address', models.EmailField(default='test@gmail.com', max_length=500)),
                ('phone', models.CharField(default='88012454784', max_length=20)),
                ('price_ragne', models.CharField(default='60$ to 7000$', max_length=50)),
                ('address', models.CharField(default='Your Address', max_length=700)),
                ('city', models.CharField(default='Your City', max_length=200)),
                ('country', models.CharField(default='Your Country', max_length=300)),
                ('state', models.CharField(default='Your State', max_length=200)),
                ('postal', models.IntegerField(default=12345)),
                ('analytics_code', models.CharField(blank=True, default='GA_MEASUREMENT_ID', max_length=300, null=True)),
                ('facebook_pixel_code', models.TextField(blank=True, null=True)),
                ('facebook_chat_code', models.TextField(blank=True, null=True)),
                ('whatsapp_is_active', models.BooleanField(default=True)),
                ('messenger_is_active', models.BooleanField(default=True)),
                ('custom_css', models.TextField(blank=True, null=True)),
                ('custom_js', models.TextField(blank=True, null=True)),
                ('currency_name', models.CharField(blank=True, default='Currency Name', max_length=100, null=True)),
                ('currency_symbol', models.CharField(blank=True, default='Currency Symbol', max_length=150, null=True)),
            ],
        ),
    ]
