# Generated by Django 4.2.4 on 2023-09-03 18:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_rename_messenger_is_active_websitesetting_facebook_chat_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerfootersetting',
            name='footer_col1_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
