# Generated by Django 4.2.4 on 2023-09-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_alter_headerfootersetting_footer_col1_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='websitesetting',
            old_name='logo',
            new_name='logo_dark',
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='logo_light',
            field=models.ImageField(default='', upload_to='app_config/'),
            preserve_default=False,
        ),
    ]
