# Generated by Django 4.2.4 on 2023-09-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_remove_headerfootersetting_quick_link_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerfootersetting',
            name='facebook',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='headerfootersetting',
            name='instagram',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='headerfootersetting',
            name='linkedin',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='headerfootersetting',
            name='twitter',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
