# Generated by Django 4.2.4 on 2023-09-15 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_alter_headerfootersetting_facebook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seosetting',
            name='social_share_image',
        ),
    ]
