# Generated by Django 4.2.4 on 2023-09-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_remove_seosetting_social_share_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seosetting',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seosetting',
            name='meta_image',
            field=models.ImageField(blank=True, null=True, upload_to='app_config/'),
        ),
        migrations.AlterField(
            model_name='seosetting',
            name='meta_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
