# Generated by Django 4.2.4 on 2023-09-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_alter_seosetting_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesetting',
            name='map_iframe',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
