# Generated by Django 4.2.4 on 2023-09-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_websitesetting_map_iframe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesetting',
            name='map_iframe',
            field=models.TextField(blank=True, null=True),
        ),
    ]
