# Generated by Django 4.2.4 on 2023-09-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0012_websitesetting_slider_particle_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesetting',
            name='custom_menu_is_active',
            field=models.BooleanField(default=False),
        ),
    ]
