# Generated by Django 4.2.4 on 2023-09-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0013_websitesetting_custom_menu_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitesetting',
            name='custom_menu_is_active',
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='default_menu_is_active',
            field=models.BooleanField(default=True),
        ),
    ]
