# Generated by Django 4.2.4 on 2023-09-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0014_remove_websitesetting_custom_menu_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesetting',
            name='magic_cursor_is_active',
            field=models.BooleanField(default=True),
        ),
    ]
