# Generated by Django 4.2.4 on 2023-09-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0015_websitesetting_magic_cursor_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesetting',
            name='contact_form_image',
            field=models.ImageField(blank=True, null=True, upload_to='app_config/'),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='price_ragne',
            field=models.CharField(blank=True, default='60$ to 7000$', max_length=50, null=True),
        ),
    ]
