# Generated by Django 4.2.4 on 2023-10-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0016_websitesetting_contact_form_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerfootersetting',
            name='footer_col1_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='headerfootersetting',
            name='footer_copyright',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='headerfootersetting',
            name='header_button_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='headerfootersetting',
            name='header_button_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='seosetting',
            name='seo_keywords',
            field=models.TextField(blank=True, default='software,application,marketer,developer', null=True),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='address',
            field=models.CharField(blank=True, default='Your Address', max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='city',
            field=models.CharField(blank=True, default='Your City', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='country',
            field=models.CharField(blank=True, default='Your Country', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='email_address',
            field=models.EmailField(blank=True, default='test@gmail.com', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='app_config/'),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='logo_dark',
            field=models.ImageField(blank=True, null=True, upload_to='app_config/'),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='logo_light',
            field=models.ImageField(blank=True, null=True, upload_to='app_config/'),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='name',
            field=models.CharField(blank=True, default='Application Name', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='phone',
            field=models.CharField(blank=True, default='88012454784', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='postal',
            field=models.IntegerField(blank=True, default=12345, null=True),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='state',
            field=models.CharField(blank=True, default='Your State', max_length=200, null=True),
        ),
    ]
