# Generated by Django 4.2.6 on 2023-10-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0017_alter_headerfootersetting_footer_col1_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesetting',
            name='show_call_now_widget',
            field=models.BooleanField(default=True),
        ),
    ]
