# Generated by Django 4.2.6 on 2023-10-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0018_websitesetting_show_call_now_widget'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesetting',
            name='twilio_auth_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='twilio_from_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='twilio_sid',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
