# Generated by Django 5.0.3 on 2024-03-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0020_rename_facebook_headerfootersetting_social1_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='templateSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template1', models.BooleanField(default=True)),
                ('template2', models.BooleanField(default=False)),
            ],
        ),
    ]
