# Generated by Django 4.2.4 on 2023-08-31 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='serviceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=500)),
                ('fontawesome_icon_class', models.CharField(max_length=100)),
                ('detail_page_image', models.ImageField(upload_to='Services/')),
                ('detail_page_description', models.TextField()),
            ],
            options={
                'verbose_name_plural': '1. Services',
            },
        ),
    ]
