# Generated by Django 4.2.4 on 2023-08-31 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_servicesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=200)),
                ('long_description', models.TextField()),
                ('ranking_number', models.IntegerField()),
                ('tag_line', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': '3. About Section',
            },
        ),
        migrations.AlterModelOptions(
            name='servicesection',
            options={'verbose_name_plural': '2. Service Section'},
        ),
        migrations.AlterModelOptions(
            name='slidersection',
            options={'verbose_name_plural': '1. Slider Section'},
        ),
    ]
