# Generated by Django 4.2.4 on 2023-08-31 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_aboutsection_alter_servicesection_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='funFactSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fontawesome_icon_class', models.CharField(max_length=200)),
                ('count', models.IntegerField()),
                ('count_after', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': '4. Fun Fact Section',
            },
        ),
    ]
