# Generated by Django 4.2.4 on 2023-08-31 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_projectcategory_projectsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Clients/')),
            ],
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
