# Generated by Django 4.2.4 on 2023-08-31 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_clientsection_alter_projectcategory_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientsection',
            options={'verbose_name_plural': '6.Client Section'},
        ),
    ]
