# Generated by Django 4.2.4 on 2023-08-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_clientsection_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='testimonialsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='Testimonials/')),
                ('star', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': '7.Testimonial Section',
            },
        ),
    ]
