# Generated by Django 4.2.4 on 2023-08-31 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_testimonialssection'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='image',
            field=models.ImageField(default='', upload_to='AboutSection/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='video_thumbnail',
            field=models.ImageField(default='', upload_to='AboutSection/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='video_url',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
