# Generated by Django 4.2.4 on 2023-09-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_servicesection_detail_page_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcategory',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
