# Generated by Django 4.2.4 on 2023-09-19 15:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_projectsection_slug_servicesection_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesection',
            name='detail_page_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
