# Generated by Django 4.2.4 on 2023-09-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_servicesection_detail_page_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesection',
            name='show_call_now_widget',
            field=models.BooleanField(default=True),
        ),
    ]
