# Generated by Django 4.2.4 on 2023-09-19 17:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_servicesection_show_call_now_widget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsection',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
