# Generated by Django 4.2.6 on 2023-10-29 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_aboutsection_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsection',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.projectcategory'),
        ),
    ]
