# Generated by Django 5.0.3 on 2025-02-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_projectsection_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientsection',
            options={'verbose_name_plural': '6. Client Section'},
        ),
        migrations.AlterModelOptions(
            name='homepageseo',
            options={'verbose_name_plural': '8. Home Page SEO'},
        ),
        migrations.AlterModelOptions(
            name='projectcategory',
            options={'verbose_name_plural': 'Project Categories'},
        ),
        migrations.AlterModelOptions(
            name='projectsection',
            options={'verbose_name_plural': '5. Project Section'},
        ),
        migrations.AlterModelOptions(
            name='testimonialssection',
            options={'verbose_name_plural': '7. Testimonial Section'},
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='projectsection',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='servicesection',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
