# Generated by Django 4.2.4 on 2023-09-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_aboutpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='years_of_experience',
            field=models.CharField(max_length=200),
        ),
    ]
