# Generated by Django 4.2.4 on 2023-09-16 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_aboutpage_years_of_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutpage',
            old_name='button1_text',
            new_name='feature1',
        ),
        migrations.RenameField(
            model_name='aboutpage',
            old_name='button2_text',
            new_name='feature2',
        ),
        migrations.RenameField(
            model_name='aboutpage',
            old_name='button3_text',
            new_name='feature3',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='button1_url',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='button2_url',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='button3_url',
        ),
    ]
