# Generated by Django 4.2.4 on 2023-10-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_rename_button1_text_aboutpage_feature1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='feature1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='feature2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='feature3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='AboutPage/'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='AboutPage/'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='AboutPage/'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='years_of_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teamsection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Teams/'),
        ),
        migrations.AlterField(
            model_name='teamsection',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teamsection',
            name='position',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
